### ISSUE TITLE
Import in ObjC project

### ISSUE THREAD

**Issue by ImHatman** [Lawlietop/KYFloatingActionButton#1]
Hi,

is your pod compatible with ObjC ? Even with use_framework! in my Podfile I cannot access your classes.

I tryed : @import KYFloatingActionButton;  .. but useless
I actually can declare my KYButton outlet and make it compile by adding @class KYButton; and at runtime it  loads your button, I can tap on it, it works :) The thing is, I cannot really access your KYButton while coding. I cannot access any of the properties :/ For example, if I try to set the delegate, Xcode just don't find the kyDelegate property and won't compile.

Autocomplete give me this :
#import <KYFloatingActionButton/KYFloatingActionButton-Swift.h>
#import <KYFloatingActionButton/KYFloatingActionButton-umbrella.h>

but none of them helps. I also tryed with despair to import your classes with a bridging-header, which I kinda knew it would be useless.

Is there a hope I can use your button in my ObjC projet ? :)

**Comment by Lawlietop** [comment]
Hello
Sorry i am new here , i try to figure out the problem .
it cause by i didn't open module,   and the following is what i fix ,  i can use it with objc 
you test it  , if find any question just tell me thank you

[Classes.zip](https://github.com/Lawlietop/KYFloatingActionButton/files/1040755/Classes.zip)
